css refactor: Delete _mixins.scss
As of [this PR][0] which removed the mixin usage in the podcast CSS, I
think that all of the usages of the SCSS mixins have been converted to
CSS.

To test, aside for grepping for mixin usages, I did:

- re-added the mixin usage from the previously mentioned [podcast PR][0]
- ran `bundle exec rails assets:precompile`, observed no errors
- modified the re-added mixin's name to "foo-podcast-subscribe-button"
- ran `bundle exec rails assets:clobber assets:precompile`, observed a compilation error:

    ```sh
    SassC::SyntaxError: Error: no mixin named podcast-subscribe-button (SassC::SyntaxError)
            on line 112:18 of app/assets/stylesheets/2017/views/_podcast.scss
            from line 38:9 of app/assets/stylesheets/2017.scss
    >>         @include podcast-subscribe-button("rss");
    ```

- applied this patch (removing the mixin file completely)
- ran `bundle exec rails assets:clobber assets:precompile`, observed no errors

[0]:https://github.com/crimethinc/website/pull/5562/changes

---

- related-to: https://github.com/crimethinc/website/issues/5349
- related-to: https://github.com/crimethinc/website/pull/5562