Version bump connection_pool from 3.0.1 to 3.0.2 (#4994)
# connection_pool from 3.0.1

v3.0.0 had breaking changes: changing positional args to keyword args

which was breaking `bundle assets:precompile` 

https://github.com/mperham/connection_pool/blob/main/Changes.md#300

> **BREAKING CHANGES** `ConnectionPool` and `ConnectionPool::TimedStack`
now use keyword arguments rather than positional arguments everywhere.
Expected impact is minimal as most people use the with API, which is
unchanged.


```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       ArgumentError: wrong number of arguments (given 1, expected 0) (ArgumentError)
```

---

# connection_pool 3.0.2

`3.0.2` fixed it

https://github.com/mperham/connection_pool/blob/main/Changes.md#302

> Support :name keyword for backwards compatibility [#210]